config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :rooms
  resources :reservations
  get 'search' => 'rooms#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations
    has_one_attached :room_image
    def self.search(keyword)
      where(["address like? OR room_name like?", "%#{keyword}%", "%#{keyword}%"])
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :user_image
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private    
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    progressday = day(@reservation.start_day,@reservation.end_day)
    @reservation.total_price = total_price(@reservation.room.price,@reservation.people,progressday)
    if @reservation.save
      redirect_to  :reservations, notice: "予約しました。"
    else
      render :new, alert: "予約されませんでした。"
    end
  end
  
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to "/reservations",notice: "予約を取り消しました。"
  end
  
  private
  
  def reservation_params
    params.require(:reservation).permit(:start_day, :end_day, :people, :user_id, :room_id, :total_price)
  end
  
  def day(startday,endday)
    endday - startday
  end
  
  def total_price(price,people,day)
    price * people * day
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      redirect_to :rooms
    else
      render :new
    end
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to room_path(@room), notice: "ルームを更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to :rooms
  end
  
  def search
    @rooms = Room.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end
  
  private
  def room_params
    params.require(:room).permit(:room_name, :introduction, :price, :address, :user_id, :room_image)
  end
  
  def reservation_params
    params.require(:reservation).permit(:start_day, :end_day, :people, :user_id, :proom_id, :total_price)
  end
  
  def total_price(price,people)
    price*people
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :user_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="section-title">
  innapp
</div>
<article class="home-index">
  <div class="home-search">
    <p>場所やキーワードで検索してみよう</p>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Innapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="search-form">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, value: @keyword %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <p class="control">
        <%= link_to "ユーザー一覧", :users, class:"header-buttom" %>
      </p>
      <p class="control">
        <%= link_to "ルーム一覧", :rooms, class:"header-buttom" %>
      </p>
      <% if user_signed_in? %>
      <p class="control">
        <%= link_to "ルーム登録", new_room_path, class:"header-buttom" %>
      </p>
      <p class="control">
        <%= link_to "予約一覧", :reservations, class:"header-buttom" %>
      </p>
      <p class="control">
        <%= link_to "マイページ", user_path(current_user), class:"header-buttom" %>
      </p>
      <p class="control">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"header-buttom" %>
      </p>
      <% else %>
      <p class="control">
        <%= link_to "新規登録", new_user_registration_path, class:"header-buttom" %>
      </p>
      <p class="control">
        <%= link_to "ログイン", new_user_session_path, class:"header-buttom" %>
      </p>
      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <p>POTEPAN</p>
    </footer>
  </body>
</html>

app/views/reservations/index.html.erb
<div class="section-title">
  予約済みルーム一覧
</div>
<article class="reservation-index">
  <table>
    <thead>
      <tr>
        <th>部屋名</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>人数</th>
        <th>合計金額</th>
        <th>予約確定日時</th>
        <th>削除</th>
      </tr>
  　</thead>
  　<tbody>
  　　<div class="reservation-list">
      　<tr>
    　　　　<% @reservations.each do |reservation| %>
          <td><%= reservation.room.room_name %></td>
      　　<td><%= reservation.start_day %></td>
      　　<td><%= reservation.end_day %></td>
      　　<td><%= reservation.people %>人</td>
      　　<td>¥<%= reservation.total_price %></td>
      　　<td><%= reservation.created_at.to_s(:datetime_jp) %></td>
      　　<% if reservation.user_id == current_user.id %>
      　 　   <td><%= link_to "削除", reservation , method: :delete, data: { confirm: "本当に削除しますか？" } %></td> 
      　　<% else %>
      　  　  <td><%= "-" %></td>
      　　<% end %>
   　　　</tr>　
   　　　　　<% end %>
  　　</div>
   　</tbody>
  </table>
</article>

app/views/rooms/edit.html.erb
<div class="section-title">
  ルーム情報編集
</div>
<article class="room-edit">
  <%= form_for @room do |f| %>
    <div class="input-label">
      <%= f.label :room_name, "部屋名" %>
    </div>
    <div class="input-form">
      <%= f.text_field :room_name %>
    </div>
    <div class="input-label">
      <%= f.label :address, "場所" %>
    </div>
    <div class="input-form">
      <%= f.text_field :address %>
    </div>
    <div class="input-label">
      <%= f.label :introduction, "説明" %>
    </div>
    <div class="input-form">
      <%= f.text_area :introduction %>
    </div>
    <div class="input-label">
      <%= f.label :price, "料金" %>
    </div>
    <div class="input-form">
      <%= f.number_field :price %>
    </div>
    <div class="input-label">
      <%= f.label :room_image, "イメージ画像" %>
    </div>
    <div class="input-form">
      <%= f.file_field :room_image %>
    </div>
    <%= f.submit "更新" %>
  <% end %>
</article>

app/views/rooms/index.html.erb
<div class="section-title">
  ルーム一覧 <%= @keyword %>
</div>
<div class="list-count">
  検索結果:<%= @rooms.count %>件
</div>
<% if user_signed_in? %>
  <% @rooms.each do |room| %>
    <div class="room-list">
      <%= link_to room, class:"list-display" do %>
        <div class="room-image">
          <%= image_tag room.room_image %>
        </div>
        <div class="room-name">
          <%= room.room_name %>
        </div>
        <br>
        <div class="room-address">
          <%= room.address %>
          </div>
          <br>
        <div class="room-price">
          ¥ <%= room.price %>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p class="nologin-message">
    ログインしてみてみよう
  </p>
  <% @rooms.each do |room| %>
    <div class="room-list">
      <%= link_to root_path, class:"list-display" do %>
        <div class="room-image">
          <%= image_tag room.room_image %>
        </div>
        <div class="room-name">
          <%= room.room_name %>
        </div>
        <br>
        <div class="room-address">
          <%= room.address %>
        </div>
        <br>
        <div class="room-price">
          ¥ <%= room.price %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/rooms/new.html.erb
<div class="section-title">
    新規ルーム登録
</div>
<div class="register-form">
  <%= form_with model: @room do |f| %>
　　<div class="input-label">
　　  <%= f.label :room_name ,"名前" %>
　　</div>
　　<div class="input-form">
　　  <%= f.text_field :room_name %>
　　</div>
    <div class="input-label">
      <%= f.label :introduction ,"部屋説明" %>
    </div>
　　<div class="input-form">
　　  <%= f.text_area :introduction %>
　　</div>
    <div class="input-label">
      <%= f.label :price ,"料金" %>
    </div>
　　<div class="input-form">
　　  <%= f.number_field :price %>
　　</div>
　　<div class="input-label">
　　  <%= f.label :address ,"場所" %>
　　</div>
　　<div class="input-form">
　　  <%= f.text_field :address %>
　　</div>
　　<div class="input-label">
　　  <%= f.label :room_image,"画像" %>
　　</div>
    <div class="input-form">
      <%= f.file_field :room_image %>
    </div>
    <p><%= f.submit "登録する"%></p>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="section-title">
  ルーム詳細
</div>
<div class="reserve-form">
  <h1>予約内容</h1>
  <%= form_with model: @reservation do |f| %>
　　<p>
　　  <%= f.label :start_day ,"開始日" %>
　　　<%= f.date_select :start_day %>
　　</p>
    <p>
      <%= f.label :end_day ,"終了日" %>
　　　<%= f.date_select :end_day %>
　　</p>
    <p>
      <%= f.label :people ,"人数" %>
　　　<%= f.number_field :people %>
　　</p>
　　<%= f.hidden_field :room_id, value: @room.id %>
　　<%= f.hidden_field :user_id, value: current_user.id %>
    <p><%= f.submit "予約する"%></p>
  <% end %>
</div>

<div class="roomshow-items">
  <div class="roomshow-image">
　　<%= image_tag @room.room_image %>
　</div>
　<div class="roomshow-item">
    部屋名<span><%= @room.room_name %></span>
　</div>
　<div class="roomshow-item">
    提供ユーザー<span><%= @room.user.name %></span>
　</div>
　<div class="roomshow-item">
    場所<span><%= @room.address %></span>
　</div>
　<div class="roomshow-item">
    説明<span><%= @room.introduction %></span>
　</div>
　<div class="roomshow-item">
    料金<span><%= @room.price %>円</span>
  </div>
　<% if @room.user.id == current_user.id %>
    <buttom>
      <%= link_to "編集画面へ", edit_room_path(@room), class:"current-buttom" %>
    </buttom>
    <buttom>
      <%= link_to "削除", @room, method: :delete, data: { confirm: "本当に削除しますか？" }, class:"current-buttom" %>
    </buttom>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="section-title">
  ユーザー情報編集
</div>
<article class="user-edit">
  <%= form_for @user do |f| %>
    <div class="input-label">
      <%= f.label :name, "Name" %>
    </div>
    <div class="input-form">
      <%= f.text_field :name %>
    </div>
    <div class="input-label">
      <%= f.label :email, "Email" %>
    </div>
    <div class="input-form">
      <%= f.email_field :email %>
    </div>
    <div class="input-label">
      <%= f.label :user_image, "プロフィール画像" %>
    </div>
    <div class="input-form">
      <%= f.file_field :user_image %>
    </div>
    <%= f.submit "更新" %>
  <% end %>
</article>

app/views/users/index.html.erb
<div class="section-title">
  ユーザー一覧
</div>
<div class="list-count">
  全<%= @users.count %>件
</div>
<% if user_signed_in? %>
  <% @users.each do |user| %>
    <div class="user-list">
      <%= link_to user, class:"list-display" do %>
        <div class="user-image"><%= image_tag user.user_image %></div>
        <div class="user-name"><%= user.name %></div>
      <% end %>
    </div>  
  <% end %>
<% else %>
  <p class="nologin-message">
    ログインしてみてみよう
  </p>
  <% @users.each do |user| %>
    <div class="user-list">
      <%= link_to root_path, class:"list-display" do %>
        <div class="user-image"><%= image_tag user.user_image %></div>
        <div class="user-name"><%= user.name %></div>
      <% end %>
    </div>  
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="section-title">
  ユーザー詳細
</div>
<article class="user-show">
  <div class="user-image">
    <%= image_tag @user.user_image %>
  </div>
  <p><%= @user.name %></p>
  <% if @user.id == current_user.id %> 
    <%= @user.email %>
    <%= link_to "編集", edit_user_path(@user) %>
  <% end %>
  <p class="subheading-user">
    <%= @user.name %>の投稿一覧
  </p>
  <div class="list-count">
    全<%= @user.rooms.count %>件
  </div>
  <% @user.rooms.each do |room| %>
    <%= link_to room do %>
      <div class="room-list">
        <div class="room-image">
          <%= image_tag room.room_image %>
        </div>
        <div class="room-name">
          <%= room.room_name %>
        </div>
        <br>
        <div class="room-address">
          <%= room.address %>
        </div>
        <br>
        <div class="room-price">
          ¥ <%= room.price %>
        </div>
        <% if @user.id == current_user.id %>
          <%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</article>
               
              
                